name: reverse-shell

on: workflow_dispatch

jobs:
  reverse:
    runs-on: ubuntu-latest

    steps:
      - name: Install ssh
        run: sudo apt update && sudo apt install -y openssh-client

      - name: Reverse SSH
        run: |
            sudo service ssh start
            ssh -o StrictHostKeyChecking=no \
                -R 0:localhost:22 \
                serveo.net